# 로컬 개발 환경 설정
spring:
  jpa:
    show-sql: true  # 실행되는 SQL 쿼리를 콘솔에 출력합니다.
    properties:
      jakarta:
        persistence:
          # schema-generation:
          #   scripts:
          #     action: create  # create 문만 뽑겠다
          #     create-target: ./output-ddl.sql # 이 파일명으로 저장해라
          #     create-source: metadata # 엔티티 메타데이터 기반으로 생성
    hibernate:
      ddl-auto: validate # DB에는 반영 안 하고 파일만 뽑을 거니까 none 추천

  # Flyway 설정 추가
  flyway:
    enabled: true
    # 기존에 생성된 테이블이 있다면 메타데이터 테이블을 생성하여 관리 시작 (필수 설정)
    baseline-on-migrate: true
    baseline-version: 1

# 로깅 설정 (로컬은 상세하게)
logging:
  level:
    root: INFO
    showroomz: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.oauthlogin: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Sentry 설정 (로컬은 모든 트레이스 수집)
sentry:
  traces-sample-rate: 1.0 # 성능 모니터링 샘플링 비율 (로컬은 100% 수집)
  environment: local
